Knives rebalancing
Cosmic-Overlord/TerraGov-Marine-Corps pull request #172
Opened 2023-05-15 11:56 UTC by Altickium

## About The Pull Request

Ограниченное количество ножей в вендоре

## Why It's Good For The Game

Раз у нас старый револьвер и их ограниченное количество, то логично, раз у нас старые ножи, сделать их также ограниченными

## Changelog

:cl:
balance: rebalanced something
/:cl:

2023-05-15 13:07 UTC, Mrrpip commented
Эй, чувак, здесь я использую переводчик, но есть два типа объектов, которые меня интересуют, поскольку они потенциально могут обойти это обновление.

/obj/item/storage/belt/knifepouch

https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/blob/c717e3c043ab7b29dcd8438e2aab740ba8ab2f4f/code/game/objects/machinery/vending/marine_vending.dm#L288

Они начинают предварительно заполняться. Удачи в этом!

2023-05-27 14:38 UTC, sluttykitty commented
ахахаххах блять

2023-06-04 11:56 UTC, Blundir requested changes
Как уже англо господин выше подметил, сделай пауч ограниченным, а вообще нужно в дискорде обговорить нерф

2023-07-11 18:41 UTC, Blundir commented
ножи успешно выключены

2023-07-11 18:41 UTC, closed without merging