Antidrop
Cosmic-Overlord/TerraGov-Marine-Corps pull request #233
Opened 2023-08-10 03:37 UTC by hivemuscle

## About The Pull Request

Мачете! Копьё! ЛОПАТА!
Всё это теперь можно крепко сжать и не бояться, что выпадет из руки при первом же стане.

## Why It's Good For The Game

Бафф не-вали оружия ближнего боя. Всё ещё слабо на фоне своего зелёного брата.

## Changelog

:cl:
Теперь мачете, копьё и лопата обладают антидропом.
У заточенной лопаты НЕОЖИДАННО, ВНЕЗАПНО, баффнут урон до с 60 до 75 (теперь аналогичен мачете).
Лопате добавлены бамп-атаки.
Убрана возможность класть заточенную лопату в инженерную разгрузку.
/:cl:

2023-08-10 11:13 UTC, sluttykitty commented
Ты чё долбоеб

2023-08-10 12:40 UTC, blackcrystall requested changes
Когда все сделаешь, жду тебя опять.
В данный момент сырая фича и требуется доработка.
А так же баланс ченжи, их требуется убрать.

2023-08-10 12:40 UTC, blackcrystall commented on code/game/objects/items/tools/shovel_tools.dm
> +	TOGGLE_BITFIELD(flags_item, NODROP)
Дефайн полное фуфло, я знаю что разницы в скомпиленом коде не будет, но тут проблема в том что он по факту существует просто для факта существования, я требую его е использовать, а сделать по человечески, а не по ящерски.

2023-08-10 12:40 UTC, blackcrystall commented on code/game/objects/items/tools/shovel_tools.dm
> +/obj/item/tool/shovel/etool/AltClick(mob/user)
Требуется сделать её через компонент для возможности в будущем использования её где-то помимо 3-х вещей

2023-08-10 12:51 UTC, blackcrystall commented
А так же CL составлен неправильно

2023-08-10 12:54 UTC, blackcrystall commented on code/game/objects/items/tools/shovel_tools.dm
> +	to_chat(user, span_notice("You loosen the grip around [src]!"))
использовать else а не return?
:clueless:

2023-08-10 20:04 UTC, hivemuscle commented on code/modules/clothing/modular_armor/attachments/storage.dm
> +	max_w_class = WEIGHT_CLASS_NORMAL
Понимаю. Но, нет, максимальный размер какого-либо предмета помимо разложенной лопаты в списке - WEIGHT_CLASS_NORMAL, поэтому не вижу смысла прописывать исключение для разложенной лопаты.

2023-08-10 20:08 UTC, hivemuscle commented on code/game/objects/items/tools/shovel_tools.dm
> +/obj/item/tool/shovel/etool/AltClick(mob/user)
ПР, который я закрыл, подразумевал собой как раз порт элемента strappable c оффов. Блундир напомнил о скором ребейзе и сказал, что порт лучше не проводить.

2023-08-10 20:08 UTC, hivemuscle commented on code/game/objects/items/tools/shovel_tools.dm
> +	force = 75
А кому расписать важность данного баффа?

2023-08-10 20:16 UTC, hivemuscle commented on code/game/objects/items/tools/shovel_tools.dm
> +	to_chat(user, span_notice("You loosen the grip around [src]!"))
Я не умею программировать на дрим мейкере, поэтому просто спиздил код рапиры ФК. На счёт дефайна - хуй его знает, как сделать иначе. Бтв, чек ishuman есть и на анидропе щита, а значит всё же необходим(?). Ветвление сделаю нормальным, ретурн заменю на элс.

2023-08-10 20:54 UTC, hivemuscle commented
Фиксы + сложенную лопату теперь нельзя взять в антидроп и взятую в антидроп разложенную лопату нельзя сложить (это выглядит глупо, как по мне, ты же за рукоять держишься).

2023-08-11 04:02 UTC, blackcrystall commented on code/game/objects/items/tools/shovel_tools.dm
> +	force = 75
Например блундиру, если даст зеленый свет, ну тут я ничего поделать не могу

2023-08-11 04:03 UTC, blackcrystall commented on code/game/objects/items/weapons/blades.dm
> +		return ..()
Чек можно сделать красивее,
user.l_hand != src && user.r_hand != src

2023-08-11 04:08 UTC, blackcrystall reviewed
А так же, надо не забывать о том что флаг NODROP заставляет морпеха даже после смерти держать вещь в руке, это требуется тоже пофиксить.

2023-08-11 04:12 UTC, blackcrystall requested changes
Немного там я ошибся,
но в любом случае, то что выше сказано тоже следует поправить,
и еще, это конечно хорошо что крепкий хват, но нейротоксину следовало бы его тоже сбивать, поскольку он на прямую воздействует на нервную систему морпеха, заставляя его например разжать руку.

2023-08-11 04:12 UTC, blackcrystall commented on code/game/objects/items/tools/shovel_tools.dm
> +	if(NODROP)
Чек конечно интересный...

2023-08-11 10:17 UTC, hivemuscle commented
Антидроп для обычного мили сделан по образу и подобию антидропа на паверфист, щит, ФК рапиру и ракетный молот, у которых нет дропа от нейротоксина и дропа при смерти. Это уже вопрос баланса: милишники ещё больше будут бояться плевак, а смерть вообще будет лишать их оружия, что может быть и интересно, но не в реалиях, где с другим оружием подобного не происходит.
Стандартное мили оружие даже с антидропом кажется достаточно бесполезным на фоне вали: ты теряешь возможность атаковать ксеноморфа реагентами, теряешь возможность впитывать зелёную кровь, теряешь встроенный медсканнер без лока на навык и теряешь забинженную на клавишу хилку, которую можешь прожать даже в софткрите и без рук (хотя последнее два это от самого модуля, а не от оружия). Что ты за это получаешь? +15 к урону. А пока ПР не замержен - ещё и из рук при каждом стане выпадает.
В общем, чек исправил, на счёт баланса написал Блундиру. Если откажет - перепишу.

К слову, во время фикса появилась идея добавить антидроп двуручной части копья, но решил этого не делать, так как ни у вали-копья, ни у кувалды такой роскоши не имеется.

2023-08-11 13:41 UTC, hivemuscle commented
Убрал ребаланс лопаты, отправляю на ревью.

2023-08-11 13:42 UTC, hivemuscle commented on code/game/objects/items/tools/shovel_tools.dm
> +	if(NODROP)
А что с ним не так?

2023-08-13 16:03 UTC, blackcrystall requested changes
Остался минорный код ишшуй, после него уже можно давать последнее решение блундиру с мержем - да/нет.

2023-08-13 16:03 UTC, blackcrystall commented on code/game/objects/items/tools/shovel_tools.dm
> +	if(NODROP)
Ну как бы flags_item & NODROP

2023-08-18 18:47 UTC, Blundir requested changes

2023-08-30 19:59 UTC, Blundir commented
мёртвый пр, автор пропал, открою обратно если попросит

2023-08-30 19:59 UTC, closed without merging