Forbid mechanic
Cosmic-Overlord/TerraGov-Marine-Corps pull request #244
Opened 2023-08-18 00:13 UTC by homexp13

## About The Pull Request

Добавляет новую механику "запрещённых каст". Квина может по своему усмотрению выбирать определённые касты и запрещать эволюционировать/регрессировать в них. Запрет осуществляется с помощью нажатия по иконке касты в хайв статусе
![Снимок экрана 2023-08-18 030202](https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/assets/52973135/ebe705c7-9069-487d-b424-6b8b0f5f5b89)

## Why It's Good For The Game

Расширяет возможности королевы улья в сфере контроля хайва, замена регресу/банишу.
![Снимок экрана 2023-08-18 030021](https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/assets/52973135/2931f284-7998-4393-8970-df05fa2aa32e)

## Changelog

:cl:
add: Added forbid mechanic
/:cl:

2023-08-18 11:14 UTC, fe-ed commented
Наконец-то годнота

2023-08-19 23:31 UTC, Blundir requested changes
добавь запрет на бан дрона, лярвы и т4
а ещё бы админ логии и уведомление в хайв

2023-08-20 10:41 UTC, homexp13 commented
> добавь запрет на бан дрона, лярвы и т4 а ещё бы админ логи и уведомление в хайв

Сделано

2023-08-21 07:59 UTC, WaterPotassiumovich commented
Мечты сбываются

2023-08-21 08:09 UTC, sluttykitty commented
БОГОУГОДНАЯ ХУЙНЯ

2023-08-21 18:07 UTC, lorianss commented
Пу-пу-пу

2023-08-23 06:49 UTC, Adven4er commented
> [Blundir](/Blundir)

А это то нахуя?

2023-09-01 17:41 UTC, Blundir approved these changes

2023-09-01 17:42 UTC, merged