Adds plasmadrain_immune and innate_plasma_regen traits to panthera.
Cosmic-Overlord/TerraGov-Marine-Corps pull request #338
Opened 2023-10-03 07:49 UTC by Helg2

plasmadrain_immune так как у пантеры плазмы нету.
innate_plasma_regen так как реген адреналина только на траве звучит как-то тупо, если я правильно понял как работает трейт.

2023-10-04 11:35 UTC, Dgeen commented
Добавь пр на ребейз ветку

2023-10-04 14:27 UTC, Helg2 commented
Там самой пантеры нету xd

2023-10-04 16:24 UTC, Helg2 commented
Можешь подсказать как пр сделать? Гитхаб мне не позволяет нормально хоть что-либо сделать

2023-10-12 10:16 UTC, fe-ed requested changes
Чинить пантеру это хорошо, но учитывая факт того что это самая сильная Т2 каста на данный момент, стоило бы эти изменения мержить совместно с его нерфом, чтобы это окончательно не сломило рассудок маринов. (Ему бы как минимум занерфить увороты от пуль)

Если не согласен - обоснуй, Васелон скорее всего забил на баланс до ребейза.

![Rebase](https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/assets/125674585/1cbf0fb9-5f1f-4eb1-8056-57c6fb4b1c71)

2023-10-12 13:48 UTC, Helg2 commented
Придерживаюсь точки зрения что это не пантера имба, а остальные касты немного дно.
+ на ребейзе уже пр замержили

2023-10-12 23:43 UTC, fe-ed commented
> Придерживаюсь точки зрения что это не пантера имба, а остальные касты немного дно. +на ребейзе уже пр замержили

Это так не работает, пантера - наш аддон, и если он как-то не соответствует тем кастам, что уже в игре, то это проблемы пантеры. Не нужно связывать баланс одной касты и баланс чуть ли не половины игры, так проблемы не решаются.

2023-11-28 11:22 UTC, closed without merging