Откат нерфа Корана
Cosmic-Overlord/TerraGov-Marine-Corps pull request #85
Opened 2023-02-27 12:59 UTC by siegluck

## About The Pull Request

Почему-то количество слотов в Библии уменьшилось с 7 до 1, поэтому пострадал люксовый Коран из лодаутов
Возвращаю ему и только ему 7 слотов, поскольку это эксклюзивный предмет для лодаута, который так был задуман

## Why It's Bad For The Game

откат нерфа маринов

## Changelog

:cl:
fix: fix gear koran slots reduction
/:cl:

2023-02-27 13:02 UTC, sluttykitty commented
опять морпехи защищают свою имбу

2023-02-27 13:37 UTC, homexp13 commented
спидмерж

2023-02-28 00:06 UTC, Blundir requested changes
Теневой пердёж свой убери

2023-02-28 00:06 UTC, Blundir commented on code/modules/client/preferences_gear.dm
> +/datum/gear/b19
Ты зачем насрал

2023-02-28 05:46 UTC, siegluck commented on code/modules/client/preferences_gear.dm
> +/datum/gear/b19
схуяли

2023-02-28 05:57 UTC, Blundir approved these changes

2023-02-28 05:57 UTC, merged